[[Aeron]]
arch = "aarch64"
git-tree-sha1 = "4b54885ce8add33e2c38d6d72106b8fa8806df91"
os = "macos"

    [[Aeron.download]]
    sha256 = "794b6ab45c2d3995433823c47097c0bd99f618de0e90ee9906913535d3db2727"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.49.0+0/Aeron.v1.49.0.aarch64-apple-darwin.tar.gz"
[[Aeron]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcd71e9644a847d048e59a188f8f4735e0e80ce2"
libc = "glibc"
os = "linux"

    [[Aeron.download]]
    sha256 = "4d17915b6b87f4f9942c6e8867fde13b73b80230f448f04fc22668e4153c4e58"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.49.0+0/Aeron.v1.49.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Aeron]]
arch = "x86_64"
git-tree-sha1 = "63b2054ada8c2ab5cffb30d3628dda03e8c03b04"
os = "macos"

    [[Aeron.download]]
    sha256 = "e713105e96e06fbe9c8a993dd12b2ee847eb3ad5ab4e30e1cace54ff0dbc6af7"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.49.0+0/Aeron.v1.49.0.x86_64-apple-darwin.tar.gz"
[[Aeron]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dc3b966552951436d6d6c0f45a359cd2baf8e38"
libc = "glibc"
os = "linux"

    [[Aeron.download]]
    sha256 = "16c0490ab4a79b144881ca72785cd0657a304174a93b252b8b6cd5b7cdf65e1a"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.49.0+0/Aeron.v1.49.0.x86_64-linux-gnu-cxx11.tar.gz"
