[[Aeron]]
arch = "aarch64"
git-tree-sha1 = "870bd4be2f0e9c9f5d161c248d111da26fc3db54"
os = "macos"

    [[Aeron.download]]
    sha256 = "85228545271c1ff68a6a5e7824f464a1f11e2d59ae8e9d33b3e332645877909f"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.42.1+1/Aeron.v1.42.1.aarch64-apple-darwin.tar.gz"
[[Aeron]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed255164b6192dd60b5ba0c6c506c1922fbe942d"
libc = "glibc"
os = "linux"

    [[Aeron.download]]
    sha256 = "d317c4b9925d3dbbf571666a2c523b44f73c51326cd24854a4d8a8cc3aa197a6"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.42.1+1/Aeron.v1.42.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Aeron]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16a1ecad62ab01f4727143b8da1205166faf2d72"
libc = "glibc"
os = "linux"

    [[Aeron.download]]
    sha256 = "4be4cb4cd551165371e40726b694cba3a01cf828465c8fb948365dabfa7be597"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.42.1+1/Aeron.v1.42.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Aeron]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61d4f2810f96af5610e038a1f5d3a02801566560"
libc = "glibc"
os = "linux"

    [[Aeron.download]]
    sha256 = "195b416eae791365e5d3a2dafb7d0b3b0ab468bc5b906594ca2b571650287709"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.42.1+1/Aeron.v1.42.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Aeron]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "000b1d275143f7869fd07184faa7a100e929cea9"
libc = "glibc"
os = "linux"

    [[Aeron.download]]
    sha256 = "bf030476867bd9f45c0f4dab5a8c2b5e5dcf6abcf151df270bf384411ac8c17d"
    url = "https://github.com/JuliaBinaryWrappers/Aeron_jll.jl/releases/download/Aeron-v1.42.1+1/Aeron.v1.42.1.x86_64-linux-gnu-cxx11.tar.gz"
