# Autogenerated wrapper script for Aeron_jll for aarch64-apple-darwin
export aeronmd, libaeron, libaeron_archive_c_client, libaeron_driver

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Aeron")
JLLWrappers.@declare_library_product(libaeron, "@rpath/libaeron.dylib")
JLLWrappers.@declare_library_product(libaeron_archive_c_client, "@rpath/libaeron_archive_c_client.dylib")
JLLWrappers.@declare_library_product(libaeron_driver, "@rpath/libaeron_driver.dylib")
JLLWrappers.@declare_executable_product(aeronmd)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libaeron,
        "lib/libaeron.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaeron_archive_c_client,
        "lib/libaeron_archive_c_client.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaeron_driver,
        "lib/libaeron_driver.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aeronmd,
        "bin/aeronmd_s",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
