# Autogenerated wrapper script for Aeron_jll for x86_64-linux-gnu-cxx11
export aeronmd, libaeron, libaeron_archive_c_client, libaeron_driver

using CompilerSupportLibraries_jll
using Libuuid_jll
JLLWrappers.@generate_wrapper_header("Aeron")
JLLWrappers.@declare_library_product(libaeron, "libaeron.so")
JLLWrappers.@declare_library_product(libaeron_archive_c_client, "libaeron_archive_c_client.so")
JLLWrappers.@declare_library_product(libaeron_driver, "libaeron_driver.so")
JLLWrappers.@declare_executable_product(aeronmd)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Libuuid_jll)
    JLLWrappers.@init_library_product(
        libaeron,
        "lib/libaeron.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaeron_archive_c_client,
        "lib/libaeron_archive_c_client.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libaeron_driver,
        "lib/libaeron_driver.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aeronmd,
        "bin/aeronmd_s",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
